version: '3.6'

services:
  iris:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 1972
      - 52773:52773
      - 53773
    volumes:
      - ./:/irisdev/app:rw
    networks:
      - rest-sec-test

  owasp-zap:
    image: owasp/zap2docker-stable
    command: sh /irisdev/app/zap-pool/listener.sh
    networks:
      - rest-sec-test
    ports:  
      - 8090:8090
    volumes:
      - ./:/irisdev/app:rw
      - ./zap-pool:/zap/wrk/:rw

networks:
  rest-sec-test:
    driver: bridge
